### ISSUE TITLE
Crash when throwing granade to any object

### ISSUE THREAD

**Issue by PaszaVonPomiot** [sullerandras/UtilizationMonitor#8]
When I throw granade in sandbox mode to the ground it works fine but as soon as it hits tree or spawner an error occurs as shown in screenshot.

Factorio v0.16.16
UtilizationMonitor v0.3
Tested also without any other mods.

![screenshot 41](https://user-images.githubusercontent.com/5560454/34965913-0db802d8-fa58-11e7-87f2-7fe5ce2905ae.png)

**Comment by ST-DDT** [comment]
I can confirm the bug. Thanks for your report.
The bug is caused if the remove_data method is called for any entity that does not have data 
(Such as trees, enemies, decoration and belts).

The attached PR #9 contains a fix for this bug. 
You can try it out yourself, but I guess the official release will be out soon as well.

**Comment by sullerandras** [comment]
Released the new version, please check. Thanks @ST-DDT for the quick pull request!
